force-app/main/default/objects/Self_Assessment__c/Self_Assessment__c.object-meta.xml
<CustomObject>
    <description>An instance of a Self-Assessment Template for an individual participant</description>
    <label>Self-Assessment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Self-Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment__c/fields/Self_Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Template</label>
    <referenceTo>Self_Assessment_Template__c</referenceTo>
    <relationshipLabel>Self-Assessments</relationshipLabel>
    <relationshipName>Self_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/Self_Assessment_Answer__c.object-meta.xml
<CustomObject>
    <description>A participant&apos;s response to a particular Self-Assessment Question</description>
    <label>Self-Assessment Answer</label>
    <nameField>
        <displayFormat>SAA-{0000000}</displayFormat>
        <label>Self-Assessment Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <label>Answer Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Answer_Text_Area__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text_Area__c</fullName>
    <label>Answer Text Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <description>The data type of the question</description>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment__c</fullName>
    <label>Self-Assessment</label>
    <referenceTo>Self_Assessment__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Question</label>
    <referenceTo>Self_Assessment_Question__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/Self_Assessment_Question__c.object-meta.xml
<CustomObject>
    <description>An individual question in a Self-Assessment Template</description>
    <label>Self-Assessment Question</label>
    <nameField>
        <displayFormat>SAQ-{000000}</displayFormat>
        <label>Self-Assessment Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Self_Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Template</label>
    <referenceTo>Self_Assessment_Template__c</referenceTo>
    <relationshipLabel>Self-Assessment Questions</relationshipLabel>
    <relationshipName>Self_Assessment_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Template__c/Self_Assessment_Template__c.object-meta.xml
<CustomObject>
    <description>A set of questions used in self-assessments</description>
    <label>Self-Assessment Template</label>
    <nameField>
        <label>Self-Assessment Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Self-Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Question_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Rating Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Text Area</fullName>
    </customValue>
    <description>Data types for questions used in self-assessments</description>
    <masterLabel>Question Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SelfAssessmentService_Test.cls
@IsTest
private class SelfAssessmentService_Test {

    @TestSetup
    static void makeData() {
        // Set up all data needed for a single self-assessment
        SelfAssessmentTestDataFactory.setupTestData();
    }
    
    @IsTest 
    static void testGetAssessment() {
        // Get self-assessment
        Self_Assessment__c sa = [
            SELECT Id, Status__c, Self_Assessment_Template__c, 
                   (SELECT Id FROM Self_Assessment_Answers__r) 
              FROM Self_Assessment__c 
             LIMIT 1
        ];

        // SelfAssessment object to receive from service
        SelfAssessment assessment;
        
        User u = SelfAssessmentTestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');
        Test.startTest();
        System.runAs(u) {
            SelfAssessmentService service = new SelfAssessmentService(sa.Id);
            assessment = service.getAssessment();
        }
        Test.stopTest();

        Assert.areEqual(sa.Id, assessment.id, 'Should have received the original assessment');
        Assert.areEqual(sa.Status__c, assessment.status, 'Statuses should be equal');
        Assert.areEqual(sa.Self_Assessment_Answers__r.size(), assessment.answers.size(), 'Should have received an answer for each assessment answer record');
    }

    @IsTest
    static void testSaveAnswers() {
        Decimal numberAnswer = 4.00;
        String textAnswer = 'Option1';

        // Get self-assessment
        Self_Assessment__c sa = [
            SELECT Id, Status__c, Self_Assessment_Template__c, 
                   (SELECT Id FROM Self_Assessment_Answers__r) 
              FROM Self_Assessment__c 
             LIMIT 1
        ];

        Assert.isFalse(sa.Self_Assessment_Answers__r.isEmpty(), 'Should have received answers with the self-assessment');

        // Get SelfAssessment obj with child answers from service
        SelfAssessmentService service = new SelfAssessmentService(sa.Id);
        SelfAssessment assessment = service.getAssessment();

        // Fill in answers
        for (SelfAssessment.Answer ans : assessment.answers) {
            if (ans.questionType == SelfAssessmentService.QUESTION_TYPE_RATING_SCALE) {
                 ans.answerNumber = numberAnswer;
            } else {
                ans.answerText = textAnswer;
            }
        }
        
        User u = SelfAssessmentTestDataFactory.createTestUser('Rey', 'Ordonez', 'Admin');
        Test.startTest();
        System.runAs(u) {
            service.saveAnswers(assessment.answers);
        }
        Test.stopTest();

        // Get refreshed data
        List<Self_Assessment_Answer__c> refreshedAnswers = [
            SELECT Id, Self_Assessment_Question__c, Self_Assessment__c, Answer_Number__c, Answer_Text_Area__c, Question_Type__c
              FROM Self_Assessment_Answer__c
             WHERE Self_Assessment__c = :sa.Id
        ];

        for (Self_Assessment_Answer__c refAns : refreshedAnswers) {
            if (refAns.Question_Type__c == SelfAssessmentService.QUESTION_TYPE_RATING_SCALE) {
                Assert.areEqual(numberAnswer, refAns.Answer_Number__c, 'Should have received the updated number answer value');
            } else {
                Assert.areEqual(textAnswer, refAns.Answer_Text_Area__c, 'Should have received the updated text answer value');
            }
        }
    }

}