force-app/main/default/objects/Self_Assessment__c/Self_Assessment__c.object-meta.xml
<CustomObject>
    <description>An instance of a Self-Assessment Template for an individual participant</description>
    <label>Self-Assessment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Self-Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Answer__c/Self_Assessment_Answer__c.object-meta.xml
<CustomObject>
    <description>A participant&apos;s response to a particular Self-Assessment Question</description>
    <label>Self-Assessment Answer</label>
    <nameField>
        <displayFormat>SAA-{0000000}</displayFormat>
        <label>Self-Assessment Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Answer_Number__c.field-meta.xml
<CustomField>
    <fullName>Answer_Number__c</fullName>
    <label>Answer Number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Answer_Text_Area__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text_Area__c</fullName>
    <label>Answer Text Area</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help text presented to the user when encountering this field in a self-assessment</description>
    <inlineHelpText>Help text presented to the user when encountering this field in a self-assessment</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Maximum_Value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Value__c</fullName>
    <label>Maximum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question text at the time it was answered</description>
    <inlineHelpText>The question text at the time it was answered</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <description>The data type of the question</description>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment__c</fullName>
    <label>Self-Assessment</label>
    <referenceTo>Self_Assessment__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Question</label>
    <referenceTo>Self_Assessment_Question__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question appeared in the self-assessment</description>
    <inlineHelpText>The order in which this question appeared in the self-assessment</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <description>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</description>
    <inlineHelpText>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</inlineHelpText>
    <label>Step</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/Self_Assessment_Question__c.object-meta.xml
<CustomObject>
    <description>An individual question in a Self-Assessment Template</description>
    <label>Self-Assessment Question</label>
    <nameField>
        <displayFormat>SAQ-{000000}</displayFormat>
        <label>Self-Assessment Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help text to present to the user when encountering this field in a self-assessment</description>
    <inlineHelpText>Help text to present to the user when encountering this field in a self-assessment</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Maximum_Value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Value__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Minimum_Value__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Value__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Minimum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question should appear in the self-assessment. Lowest numbers appear first. Nulls last.</description>
    <inlineHelpText>The order in which this question should appear in the self-assessment. Lowest numbers appear first. Nulls last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</description>
    <inlineHelpText>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</inlineHelpText>
    <label>Step</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Question_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Rating Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Text Area</fullName>
    </customValue>
    <description>Data types for questions used in self-assessments</description>
    <masterLabel>Question Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SelfAssessmentService.cls
/*********************************************
 * Service class for self-assessments
 * @date 2024
 *********************************************/
public with sharing class SelfAssessmentService {

    public Id selfAssessmentId {get; private set;}
    public List<Answer> answers {get; private set;}
    
    /**
     * Constructor accepts a self assessment record id and loads related answers
     */
    public SelfAssessmentService(Id selfAssessmentId) {
        this.selfAssessmentId = selfAssessmentId;
        this.answers = getAnswers();
    }

    /**
     * Creates Answer data wrapper objects for each Self-Assessment Answer sObject
     *  related to the instance's selfAssessmentId
     * Only fetches answers once, then returns from cache
     * @return Answer[]
     */
    private List<Answer> getAnswers() {
        if (answers == null) {
            answers = new List<Answer>();
            for (Self_Assessment_Answer__c obj : getAnswerSObjects()) {
                Answer ans = new Answer();
                ans.id = obj.Id;
                ans.selfAssessmentId = obj.Self_Assessment__c;
                ans.questionId = obj.Self_Assessment_Question__c;
                ans.question = obj.Question__c;
                ans.sortOrder = obj.Sort_Order__c;
                ans.questionType = obj.Question_Type__c;
                ans.helpText = obj.Help_Text__c;
                ans.required = obj.Required__c;
                ans.minValue = obj.Minimum_Value__c;
                ans.maxValue = obj.Maximum_Value__c;
                ans.step = obj.Step__c;
                ans.answerText = obj.Answer_Text_Area__c;
                ans.answerNumber = obj.Answer_Number__c;
                answers.add(ans);
            }
        }
        return answers;
    }

    /**
     * Query for Self-Assessment Answer sObjects related to 
     *  the instance's selfAssessmentId
     * @return Self_Assessment_Answer__c[]
     */
    private List<Self_Assessment_Answer__c> getAnswerSObjects() {
        return [
            SELECT Id, 
                   Self_Assessment__c, 
                   Self_Assessment_Question__c, 
                   Question__c, 
                   Sort_Order__c, 
                   Question_Type__c, 
                   Help_Text__c, 
                   Required__c, 
                   Minimum_Value__c, 
                   Maximum_Value__c, 
                   Step__c, 
                   Answer_Text_Area__c, 
                   Answer_Number__c
              FROM Self_Assessment_Answer__c 
             WHERE Self_Assessment__c = :selfAssessmentId
              WITH SYSTEM_MODE 
             ORDER BY Sort_Order__c ASC
             LIMIT 10000
        ];
    }

    /*********************************************
     * Data wrapper to represent Answers in lwc
     *********************************************/
     public class Answer {
        @AuraEnabled
        public Id id {get;set;}
        @AuraEnabled
        public Id selfAssessmentId {get;set;}
        @AuraEnabled
        public Id questionId {get;set;}
        @AuraEnabled
        public Decimal sortOrder {get;set;}
        @AuraEnabled
        public String questionType {get;set;}
        @AuraEnabled
        public String question {get;set;}
        @AuraEnabled
        public Boolean required {get;set;}
        @AuraEnabled
        public String helpText {get;set;}
        @AuraEnabled
        public Decimal maxValue {get;set;}
        @AuraEnabled
        public Decimal minValue {get;set;}
        @AuraEnabled
        public Decimal step {get;set;}
        @AuraEnabled
        public String answerText {get;set;}
        @AuraEnabled
        public Decimal answerNumber {get;set;}
    }

}