force-app/main/default/objects/Self_Assessment__c/Self_Assessment__c.object-meta.xml
<CustomObject>
    <description>An instance of a Self-Assessment Template for an individual participant</description>
    <label>Self-Assessment</label>
    <nameField>
        <displayFormat>SA-{000000}</displayFormat>
        <label>Self-Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Self-Assessments</relationshipLabel>
    <relationshipName>Self_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Self_Assessment_Contact_Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment__c/fields/Self_Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Template</label>
    <referenceTo>Self_Assessment_Template__c</referenceTo>
    <relationshipLabel>Self-Assessments</relationshipLabel>
    <relationshipName>Self_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/Self_Assessment_Answer__c.object-meta.xml
<CustomObject>
    <description>A participant&apos;s response to a particular Self-Assessment Question</description>
    <label>Self-Assessment Answer</label>
    <nameField>
        <displayFormat>SAA-{0000000}</displayFormat>
        <label>Self-Assessment Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help text presented to the user when encountering this field in a self-assessment</description>
    <inlineHelpText>Help text presented to the user when encountering this field in a self-assessment</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Maximum_Value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Value__c</fullName>
    <label>Maximum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question text at the time it was answered</description>
    <inlineHelpText>The question text at the time it was answered</inlineHelpText>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <description>The data type of the question</description>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment__c</fullName>
    <label>Self-Assessment</label>
    <referenceTo>Self_Assessment__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Self_Assessment_Question__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Question</label>
    <referenceTo>Self_Assessment_Question__c</referenceTo>
    <relationshipLabel>Self-Assessment Answers</relationshipLabel>
    <relationshipName>Self_Assessment_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question appeared in the self-assessment</description>
    <inlineHelpText>The order in which this question appeared in the self-assessment</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Answer__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <description>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</description>
    <inlineHelpText>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</inlineHelpText>
    <label>Step</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/Self_Assessment_Question__c.object-meta.xml
<CustomObject>
    <description>An individual question in a Self-Assessment Template</description>
    <label>Self-Assessment Question</label>
    <nameField>
        <displayFormat>SAQ-{000000}</displayFormat>
        <label>Self-Assessment Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Self-Assessment Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Display_Type__c.field-meta.xml
<CustomField>
    <fullName>Display_Type__c</fullName>
    <description>For rating scale questions, the input type when presented to users in a self-assessment form</description>
    <inlineHelpText>For rating scale questions, the input type when presented to users in a self-assessment form</inlineHelpText>
    <label>Display Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Slider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Help_Text__c.field-meta.xml
<CustomField>
    <fullName>Help_Text__c</fullName>
    <description>Help text to present to the user when encountering this field in a self-assessment</description>
    <inlineHelpText>Help text to present to the user when encountering this field in a self-assessment</inlineHelpText>
    <label>Help Text</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Maximum_Value__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Value__c</fullName>
    <defaultValue>5</defaultValue>
    <label>Maximum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Minimum_Value__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Value__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Minimum Value</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description>Available picklist values for this field. Enter values separated by semi-colons.</description>
    <inlineHelpText>Available picklist values for this field. Enter values separated by semi-colons.</inlineHelpText>
    <label>Picklist Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Self_Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Self_Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Self-Assessment Template</label>
    <referenceTo>Self_Assessment_Template__c</referenceTo>
    <relationshipLabel>Self-Assessment Questions</relationshipLabel>
    <relationshipName>Self_Assessment_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which this question should appear in the self-assessment. Lowest numbers appear first. Nulls last.</description>
    <inlineHelpText>The order in which this question should appear in the self-assessment. Lowest numbers appear first. Nulls last.</inlineHelpText>
    <label>Sort Order</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <defaultValue>1</defaultValue>
    <description>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</description>
    <inlineHelpText>The increment between each option in the rating scale. It defines the smallest difference participants can select between the Minimum Value and Maximum Value.</inlineHelpText>
    <label>Step</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Self_Assessment_Question__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The data type of the question. Select Rating Scale for a numerical score. Select Text Area for open responses.</description>
    <inlineHelpText>The data type of the question. Select Rating Scale for a numerical score. Select Text Area for open responses.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Question_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Self_Assessment_Template__c/Self_Assessment_Template__c.object-meta.xml
<CustomObject>
    <description>A set of questions used in self-assessments</description>
    <label>Self-Assessment Template</label>
    <nameField>
        <label>Self-Assessment Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Self-Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Question_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Rating Scale</fullName>
    </customValue>
    <customValue>
        <fullName>Text Area</fullName>
    </customValue>
    <description>Data types for questions used in self-assessments</description>
    <masterLabel>Question Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Self_Assessment_Contact_Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Service Participant</fullName>
    </customValue>
    <customValue>
        <fullName>Service Provider</fullName>
    </customValue>
    <masterLabel>Self-Assessment Contact Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SelfAssessmentTestDataFactory.cls
/**
 * Test data factory for self assessments.
 * TODO - Break sobject types out into separate methods for more dynamic tests.
 */

@IsTest
public with sharing class SelfAssessmentTestDataFactory {
    
    /**
     * Set up all needed records for a single self-assessment that has not been started
     */
    public static void setupTestData() {
        // Template
        Self_Assessment_Template__c template = new Self_Assessment_Template__c(
            Name = 'Test Template'
        );
        insert template;

        // Questions of various types
        List<Self_Assessment_Question__c> lstQuestions = new List<Self_Assessment_Question__c>();
        Self_Assessment_Question__c ratingScaleQuestion = new Self_Assessment_Question__c(
            Question__c = 'Test much?',
            Self_Assessment_Template__c = template.Id,
            Sort_Order__c = 1.00,
            Type__c = SelfAssessmentService.QUESTION_TYPE_RATING_SCALE, 
            Display_Type__c = 'Radio',
            Minimum_Value__c = 1,
            Maximum_Value__c = 4,
            Step__c = 1,
            Required__c = true
        );
        lstQuestions.add(ratingScaleQuestion);

        Self_Assessment_Question__c textAreaQuestion = new Self_Assessment_Question__c(
            Question__c = 'Please explain',
            Self_Assessment_Template__c = template.Id,
            Sort_Order__c = 2.00,
            Type__c = SelfAssessmentService.QUESTION_TYPE_TEXT_AREA, 
            Help_Text__c = 'A little help'
        );
        lstQuestions.add(textAreaQuestion);

        Self_Assessment_Question__c picklistQuestion = new Self_Assessment_Question__c(
            Question__c = 'Pick a test',
            Self_Assessment_Template__c = template.Id,
            Sort_Order__c = 3.00,
            Type__c = SelfAssessmentService.QUESTION_TYPE_PICKLIST, 
            Picklist_Values__c = 'Option1;Option2;Option3',
            Help_Text__c = 'A little help'
        );
        lstQuestions.add(picklistQuestion);

        Self_Assessment_Question__c mspQuestion = new Self_Assessment_Question__c(
            Question__c = 'Pick a few tests',
            Self_Assessment_Template__c = template.Id,
            Sort_Order__c = 4.00,
            Type__c = SelfAssessmentService.QUESTION_TYPE_MULTI_SELECT_PICKLIST, 
            Picklist_Values__c = 'Option1;Option2;Option3',
            Help_Text__c = 'A little help'
        );
        lstQuestions.add(mspQuestion);

        insert lstQuestions;

        // Contacts to associate with self-assessment responses
        Contact ct = new Contact(FirstName = 'Juan', LastName = 'Lagares', Email = 'juan@testing.com');
        insert ct;

        // A self-assessment for the new contact
        Self_Assessment__c sa = new Self_Assessment__c(
            Contact__c = ct.Id, 
            Self_Assessment_Template__c = template.Id, 
            Status__c = 'Not Started',
            Contact_Role__c = 'Service Participant'
        );
        insert sa;

        // Answer creation is handled in flow and will not be active during deployments.
        // Check for records and create them if they're absent
        List<Self_Assessment_Answer__c> lstAnswers = [SELECT Id FROM Self_Assessment_Answer__c WHERE Self_Assessment__c = :sa.Id];

        if (lstAnswers.isEmpty()) {
            for (Self_Assessment_Question__c q : lstQuestions) {
                Self_Assessment_Answer__c ans = new Self_Assessment_Answer__c(
                    Self_Assessment__c = sa.Id,
                    Self_Assessment_Question__c = q.Id,
                    Question_Type__c = q.Type__c,
                    Question__c = q.Question__c
                );
                if (ans.Question_Type__c == 'Rating Scale') {
                    ans.Minimum_Value__c = q.Minimum_Value__c;
                    ans.Maximum_Value__c = q.Maximum_Value__c;
                    ans.Step__c = q.Step__c;
                }
                lstAnswers.add(ans);
            }
            insert lstAnswers;
        }
    }

    /**
     * Create test user with self-assessment perm sets
     * Valid permissionLevel values are 'Admin' and 'User'
     */
    public static User createTestUser(
        String firstName, 
        String lastName, 
        String permissionLevel
    ) {
        String orgId      = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ', '').replace(':', '').replace('-', '');
        Integer randomInt = Integer.valueOf(Math.rint(Math.random() * 1000000));
        String uniqueName = orgId + dateString + randomInt;

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User u = new User();
        u.IsActive          = true;
        u.TimeZoneSidKey    = UserInfo.getTimeZone().toString();
        u.LocaleSidKey      = UserInfo.getLocale();
        u.LanguageLocaleKey = UserInfo.getLocale();
        u.EmailEncodingKey  = 'ISO-8859-1';
        u.Username          = uniqueName + '@test' + orgId + '.org';
        u.Email             = uniqueName + '@test' + orgId + '.org';
        u.FirstName         = firstName;
        u.LastName          = lastName;
        u.Alias             = uniqueName.substring(18, 23);
        u.ProfileId         = profile.Id;
        insert u;

        // Assign permission set
        if (permissionLevel != null) {
            String permSetName = 'Self_Assessment_' + permissionLevel;
            PermissionSet permSet = [SELECT Id FROM PermissionSet WHERE Name = :permSetName LIMIT 1];
            insert new PermissionSetAssignment(
                AssigneeId = u.Id,
                PermissionSetId = permSet.Id
            );
        }
        return u;
    }

}